### ISSUE TITLE
Table generation would be clearer when using treatment names

### ISSUE THREAD

**Issue by SHAESEN2** [elong0527/r4csr#7]
In the chapters TRT01PN is used, prefixed with n or pct. This makes interpretation more difficult with regard what is happening. It is more straightforwards to use the column names that you desire in the final report. These are the actual treatments #4

**Comment by elong0527** [comment]
Within a project team, I feel `TRT01PN` is easier because

1. `TRT01P` may contain special character and space. 
2. The order in `TRT01P` needs to be defined by a factor. 

For the tutorial, I would keep it simple and use `TRT01PN`, although the interpretation could be difficult for new member. 

This is also one of the reason I display a short listing at 

https://github.com/elong0527/r4csr/blob/master/tlf-disposition.Rmd#L41

**Comment by SHAESEN2** [comment]
I agree. It depends on the style of the company. In my experience newcomers struggle with the concept of using treatment codes to later replace them with the treatment decodes. Keeping it factor (eg also the numeric representation), might help the user to better understand what you are doing. For example you can quickly explain at the beginning of the chapter that you will be using treatment codes for the mentioned reasons, but explain they can be easily replaced?

**Comment by nanxstats** [comment]
Is this fixed or do we need more work?

**Comment by elong0527** [comment]
Let's close this item for now. I did not have a plan to make a global change for treatment variables. We can reopen this item if required.
